[build]
  functions = "lambda"
  base = "."
  publish = "dist"
  command = "npm run build:lambda && npm run generate"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
